version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install Terraform without using GPG keyring
      - wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - rm -rf terraform  # Remove any existing terraform directory
      - unzip -o terraform_1.5.0_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      # Install Yarn
      - npm install -g yarn
      # Debug: Check repository structure
      - echo "Repository root contents:"
      - ls -la
      - echo "Current working directory:"
      - pwd

  build:
    commands:
      # STEP 1: TERRAFORM INFRASTRUCTURE SETUP
      - echo "Setting up Infrastructure with Terraform"
      # Check if terraform directory exists
      - if [ -d "terraform" ]; then
          echo "Terraform directory exists. Listing contents:";
          ls -la terraform;
          if [ -d "terraform/frontend" ]; then
            cd terraform/frontend;
            terraform init;
            terraform workspace select ${ENVIRONMENT} || terraform workspace new ${ENVIRONMENT};
            terraform plan -var="environment=${ENVIRONMENT}" -var="frontend_bucket_name=rizzlers-frontend" -out=tfplan;
            terraform apply -auto-approve tfplan;
            cd ../..;
            echo "Terraform infrastructure created successfully";
          else
            echo "terraform/frontend directory not found";
            exit 1;
          fi
        else
          echo "Terraform directory not found";
          exit 1;
        fi

  post_build:
    commands:
      # STEP 2: FRONTEND BUILD (after infrastructure is ready)
      - echo "Building Frontend Application"
      - if [ -d "frontend" ]; then
          cd frontend;
          yarn install;
          yarn build;
          echo "Frontend build completed";
          cd ..;
        else
          echo "Frontend directory not found";
          exit 1;
        fi
      
      # STEP 3: USE TERRAFORM-CREATED RESOURCES
      - echo "Deployment complete"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
  name: frontend-build