version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install Terraform without using GPG keyring
      - wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      # Install Yarn
      - npm install -g yarn

  pre_build:
    commands:
      # Frontend Build
      - echo "Building Frontend Application"
      - yarn install
      - yarn build
      - echo "Frontend build completed"

  build:
    commands:
      # Terraform Infrastructure Setup
      - echo "Setting up Infrastructure with Terraform"
      - cd terraform/frontend
      - terraform init
      - terraform workspace select ${ENVIRONMENT} || terraform workspace new ${ENVIRONMENT}
      - terraform plan -var="environment=${ENVIRONMENT}" -var="frontend_bucket_name=rizzlers-frontend" -out=tfplan
      - terraform apply -auto-approve tfplan
      - cd ../..

  post_build:
    commands:
      # Deploy Frontend to S3 (which was just created by Terraform)
      - echo "Deploying Frontend to S3"
      - |
        BUCKET_NAME="rizzlers-frontend-${ENVIRONMENT}"
        echo "Deploying to bucket: $BUCKET_NAME"
        aws s3 sync build/ s3://$BUCKET_NAME/ --delete
      # Invalidate CloudFront
      - |
        DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Tags[?Key=='Environment'].Value, '${ENVIRONMENT}') && contains(Tags[?Key=='Name'].Value, 'rizzlers-frontend')].Id" --output text)
        if [ ! -z "$DISTRIBUTION_ID" ]; then
          echo "Invalidating CloudFront Distribution: $DISTRIBUTION_ID"
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
        fi
      - echo "Deployment Complete!"

artifacts:
  files:
    - build/**/*
    - terraform/frontend/**/*
  name: deployment-output