version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install Terraform without using GPG keyring
      - wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - rm -rf terraform  # Remove any existing terraform directory
      - unzip terraform_1.5.0_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      # Install Yarn
      - npm install -g yarn

  pre_build:
    commands:
      # Navigate to the frontend directory
      - cd frontend
      # Frontend Build
      - echo "Building Frontend Application"
      - yarn install
      - yarn build
      - echo "Frontend build completed"
      # Navigate back to the root directory
      - cd ..

  build:
    commands:
      # Debug: List current directory contents
      - echo "Listing current directory contents"
      - ls -la
      # Terraform Infrastructure Setup
      - echo "Setting up Infrastructure with Terraform"
      - cd terraform/frontend
      - terraform init
      - terraform workspace select ${ENVIRONMENT} || terraform workspace new ${ENVIRONMENT}
      - terraform plan -var="environment=${ENVIRONMENT}" -var="frontend_bucket_name=rizzlers-frontend" -out=tfplan
      - terraform apply -auto-approve tfplan
      - cd ../..

  post_build:
    commands:
      - echo "Build and Infrastructure setup complete"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
  name: frontend-build