version: 0.2

env:
  variables:
    TERRAFORM_VERSION: 1.5.7
    NODE_VERSION: 18
    DEFAULT_ENVIRONMENT: dev
  parameter-store:
    AWS_ACCESS_KEY_ID: /rizzlers/access_id
    AWS_SECRET_ACCESS_KEY: /rizzlers/secret_key

phases:
  install:
    runtime-versions:
      nodejs: $NODE_VERSION
    commands:
      - echo Installing Terraform
      - if [ -d terraform ]; then rm -rf terraform; fi
      - if [ -f terraform ]; then rm -f terraform; fi
      - wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip -o -q terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - pip install --upgrade pip
      - pip install awscli --upgrade

  pre_build:
    commands:
      - echo Creating directories
      - mkdir -p terraform/environments/dev terraform/environments/qa
      - echo Setting environment to dev
      - ENVIRONMENT=dev
      - echo Creating simple Terraform file
      - echo 'provider "aws" {region = "ap-south-1"}' > terraform/environments/$ENVIRONMENT/main.tf
      - echo 'resource "aws_s3_bucket" "frontend" {bucket = "rizzlers-frontend-dev" tags = {Name = "Rizzlers-dev", Creator = "Rizzlers Team", Purpose = "IBE"}}' >> terraform/environments/$ENVIRONMENT/main.tf
      - echo 'output "s3_bucket_name" {value = aws_s3_bucket.frontend.bucket}' >> terraform/environments/$ENVIRONMENT/main.tf
      - echo 'output "cloudfront_distribution_id" {value = "dummy-id"}' >> terraform/environments/$ENVIRONMENT/main.tf
      - cd terraform/environments/$ENVIRONMENT
      - terraform init

  build:
    commands:
      - terraform apply -auto-approve
      - export S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name)
      - export CLOUDFRONT_DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)
      - echo $S3_BUCKET_NAME > bucket-name.txt
      - echo $CLOUDFRONT_DISTRIBUTION_ID > cloudfront-id.txt
      - cd ../../../
      - mkdir -p frontend/dist
      - echo Hello World > frontend/dist/index.html
      - cp terraform/environments/$ENVIRONMENT/bucket-name.txt frontend/dist/
      - cp terraform/environments/$ENVIRONMENT/cloudfront-id.txt frontend/dist/

  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - frontend/dist/**/*
    - terraform/environments/dev/bucket-name.txt
    - terraform/environments/dev/cloudfront-id.txt
  base-directory: .
  discard-paths: no

cache:
  paths:
    - frontend/node_modules/**/* 