name: Terraform and Frontend Deployment - Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  # Add a test job before terraform
  test:
    name: "Run Tests - Dev"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        
      - name: Use Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Enable Corepack
        run: |
          corepack enable
          yarn --version
          
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
          
      - name: Run Tests
        run: yarn test
        
      - name: Generate Coverage Report
        run: yarn run coverage
        
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: frontend/coverage
          retention-days: 7

  terraform:
    name: "Terraform for Dev"
    runs-on: ubuntu-latest
    # Only run this job on direct push to dev
    if: github.ref == 'refs/heads/dev'
    permissions:
      contents: read
    # Make terraform job depend on successful test run
    needs: test
    
    defaults:
      run:
        working-directory: terraform
    
    outputs:
      environment: ${{ steps.workspace.outputs.WORKSPACE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Create terraform directory and modules structure if it doesn't exist
      - name: Setup Terraform Directory
        run: |
          mkdir -p modules/frontend/s3
          mkdir -p modules/frontend/cloudfront
        working-directory: .

      # Create terraform configuration files for frontend resources
      - name: Create Terraform Configuration Files
        run: |
          cat <<EOF > main.tf
          terraform {
            required_providers {
              aws = {
                source  = "hashicorp/aws"
                version = "~> 5.0"
              }
            }
          }

          provider "aws" {
            region = "ap-south-1"
            default_tags {
              tags = {
                Creator = "RizzlersTeam"
                Purpose = "IBE"
                Environment = terraform.workspace
              }
            }
          }

          module "frontend_s3" {
            source = "./modules/frontend/s3"
          }

          module "frontend_cloudfront" {
            source                      = "./modules/frontend/cloudfront"
            bucket_name                 = module.frontend_s3.bucket_name
            bucket_regional_domain_name = module.frontend_s3.bucket_regional_domain_name
            depends_on                  = [module.frontend_s3]
          }

          output "cloudfront_distribution_domain" {
            description = "The domain name of the CloudFront distribution"
            value       = module.frontend_cloudfront.cloudfront_distribution_domain
          }
          
          output "bucket_name" {
            description = "The name of the S3 bucket"
            value       = module.frontend_s3.bucket_name
          }
          
          output "environment" {
            description = "Current environment (workspace)"
            value       = terraform.workspace
          }
          EOF

          cat <<EOF > backend.tf
          terraform {
            backend "s3" {
              bucket         = "rizzlers-ibe-dev-tfstate"
              key            = "frontend/terraform.tfstate"
              region         = "ap-south-1"
              encrypt        = true
              dynamodb_table = "rizzlers-terraform-locks"
            }
          }

          # Use a data source to check if the DynamoDB table already exists
          data "aws_dynamodb_table" "existing_locks_table" {
            name = "rizzlers-terraform-locks"
            # This will fail if the table doesn't exist, but that's okay because we use count below
            count = 1
          }

          # Create the DynamoDB table for state locking only if it doesn't exist
          resource "aws_dynamodb_table" "terraform_locks" {
            # Only create if the data source lookup fails (i.e., the table doesn't exist)
            count        = length(data.aws_dynamodb_table.existing_locks_table) > 0 ? 0 : 1
            name         = "rizzlers-terraform-locks"
            billing_mode = "PAY_PER_REQUEST"
            hash_key     = "LockID"

            attribute {
              name = "LockID"
              type = "S"
            }

            tags = {
              Name    = "Rizzlers-Terraform-State-Lock"
              Creator = "RizzlersTeam"
              Purpose = "IBE"
            }

            # This prevents Terraform from trying to delete this table when running terraform destroy
            # since it's needed for the state locking mechanism
            lifecycle {
              prevent_destroy = true
            }
          }
          EOF

          cat <<EOF > modules/frontend/s3/main.tf
          locals {
            bucket_name = "rizzlers-ibe-frontend-\${terraform.workspace}"
          }

          # Use a data source to check if the bucket already exists
          data "aws_s3_bucket" "existing_bucket" {
            bucket = local.bucket_name
            count  = 1
          }

          resource "aws_s3_bucket" "frontend" {
            bucket = local.bucket_name
            
            tags = {
              Name = "Rizzlers-Frontend-S3-\${terraform.workspace}"
            }

            # Don't recreate if only these attributes change
            lifecycle {
              ignore_changes = [
                tags,
                server_side_encryption_configuration
              ]
            }
          }

          resource "aws_s3_bucket_ownership_controls" "frontend" {
            bucket = aws_s3_bucket.frontend.id
            rule {
              object_ownership = "BucketOwnerPreferred"
            }
          }

          resource "aws_s3_bucket_public_access_block" "frontend" {
            bucket = aws_s3_bucket.frontend.id

            block_public_acls       = false
            block_public_policy     = false
            ignore_public_acls      = false
            restrict_public_buckets = false
          }

          resource "aws_s3_bucket_acl" "frontend" {
            depends_on = [
              aws_s3_bucket_ownership_controls.frontend,
              aws_s3_bucket_public_access_block.frontend,
            ]

            bucket = aws_s3_bucket.frontend.id
            acl    = "public-read"
          }

          resource "aws_s3_bucket_website_configuration" "frontend" {
            bucket = aws_s3_bucket.frontend.id
            
            index_document {
              suffix = "index.html"
            }
            
            error_document {
              key = "index.html"
            }
          }

          resource "aws_s3_bucket_policy" "frontend" {
            bucket     = aws_s3_bucket.frontend.id
            depends_on = [aws_s3_bucket_public_access_block.frontend]
            
            policy = jsonencode({
              Version = "2012-10-17"
              Statement = [
                {
                  Effect    = "Allow"
                  Principal = "*"
                  Action    = "s3:GetObject"
                  Resource  = "\${aws_s3_bucket.frontend.arn}/*"
                }
              ]
            })
          }

          output "bucket_name" {
            description = "The name of the S3 bucket"
            value       = aws_s3_bucket.frontend.id
          }

          output "bucket_regional_domain_name" {
            description = "The regional domain name of the S3 bucket"
            value       = aws_s3_bucket.frontend.bucket_regional_domain_name
          }

          output "website_endpoint" {
            description = "The website endpoint of the S3 bucket"
            value       = aws_s3_bucket_website_configuration.frontend.website_endpoint
          }
          EOF

          cat <<EOF > modules/frontend/cloudfront/main.tf
          resource "aws_cloudfront_origin_access_identity" "frontend" {
            comment = "OAI for Rizzlers Frontend - \${terraform.workspace}"
          }

          resource "aws_cloudfront_distribution" "frontend" {
            enabled             = true
            is_ipv6_enabled     = true
            default_root_object = "index.html"
            price_class         = "PriceClass_100"
            
            origin {
              domain_name = var.bucket_regional_domain_name
              origin_id   = "S3-rizzlers-frontend-\${terraform.workspace}"
              
              custom_origin_config {
                http_port              = 80
                https_port             = 443
                origin_protocol_policy = "http-only"
                origin_ssl_protocols   = ["TLSv1.2"]
              }
            }
            
            default_cache_behavior {
              allowed_methods  = ["GET", "HEAD", "OPTIONS"]
              cached_methods   = ["GET", "HEAD"]
              target_origin_id = "S3-rizzlers-frontend-\${terraform.workspace}"
              
              forwarded_values {
                query_string = false
                
                cookies {
                  forward = "none"
                }
              }
              
              viewer_protocol_policy = "redirect-to-https"
              min_ttl                = 0
              default_ttl            = 3600
              max_ttl                = 86400
            }
            
            restrictions {
              geo_restriction {
                restriction_type = "none"
              }
            }
            
            viewer_certificate {
              cloudfront_default_certificate = true
            }
            
            custom_error_response {
              error_code         = 403
              response_code      = 200
              response_page_path = "/index.html"
            }
            
            custom_error_response {
              error_code         = 404
              response_code      = 200
              response_page_path = "/index.html"
            }
            
            tags = {
              Name = "Rizzlers-Frontend-CloudFront-\${terraform.workspace}"
            }

            # Prevent recreation issues
            lifecycle {
              ignore_changes = [
                tags,
                viewer_certificate
              ]
            }
          }

          output "cloudfront_distribution_domain" {
            description = "The domain name of the CloudFront distribution"
            value       = aws_cloudfront_distribution.frontend.domain_name
          }
          EOF

          cat <<EOF > modules/frontend/cloudfront/variables.tf
          variable "bucket_name" {
            description = "Name of the S3 bucket"
            type        = string
          }

          variable "bucket_regional_domain_name" {
            description = "Regional domain name of the S3 bucket"
            type        = string
          }
          EOF
        working-directory: terraform

      - name: Create DynamoDB table for state locking (if it doesn't exist)
        run: |
          # Check if the DynamoDB table exists
          if ! aws dynamodb describe-table --table-name rizzlers-terraform-locks &> /dev/null; then
            echo "Creating DynamoDB table for Terraform state locking..."
            aws dynamodb create-table \
              --table-name rizzlers-terraform-locks \
              --billing-mode PAY_PER_REQUEST \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --tags Key=Name,Value=Rizzlers-Terraform-State-Lock Key=Creator,Value=RizzlersTeam Key=Purpose,Value=IBE
            echo "DynamoDB table created."
          else
            echo "DynamoDB table for state locking already exists."
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Set workspace to dev for dev branch
      - name: Set Terraform Workspace
        id: workspace
        run: |
          echo "WORKSPACE=dev" >> $GITHUB_ENV
          echo "WORKSPACE=dev" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: |
          terraform workspace select ${{ env.WORKSPACE }} || terraform workspace new ${{ env.WORKSPACE }}

      - name: Terraform Format
        run: terraform fmt
        continue-on-error: true

      - name: Import Existing Resources
        run: |
          # First check if resources exist in state already
          if ! terraform state list | grep -q "aws_dynamodb_table.terraform_locks"; then
            echo "Attempting to import DynamoDB table..."
            terraform import 'data.aws_dynamodb_table.existing_locks_table[0]' rizzlers-terraform-locks || true
          fi
          
          # Import S3 bucket if it exists
          BUCKET_NAME="rizzlers-ibe-frontend-${{ env.WORKSPACE }}"
          if ! terraform state list | grep -q "module.frontend_s3.aws_s3_bucket.frontend"; then
            echo "Attempting to import S3 bucket..."
            terraform import 'module.frontend_s3.data.aws_s3_bucket.existing_bucket[0]' $BUCKET_NAME || true
          fi
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        continue-on-error: true
        
      - name: Set S3 Bucket Name
        id: set_bucket
        run: |
          # Use a hardcoded bucket name based on workspace
          echo "S3_BUCKET=rizzlers-ibe-frontend-${{ env.WORKSPACE }}" >> $GITHUB_ENV
        
      - name: Get CloudFront Domain
        id: cloudfront_domain
        run: |
          # Try to get the CloudFront domain if available, but don't fail if it's not
          CF_DOMAIN=$(terraform output cloudfront_distribution_domain || echo "")
          if [ ! -z "$CF_DOMAIN" ]; then
            # Remove quotes if present
            CF_DOMAIN=$(echo $CF_DOMAIN | tr -d '"')
            echo "CLOUDFRONT_DOMAIN=$CF_DOMAIN" >> $GITHUB_ENV
            echo "CloudFront domain: $CF_DOMAIN"
          else
            echo "CloudFront domain not available yet"
          fi
        continue-on-error: true

  build-and-deploy:
    name: "Build and Deploy Frontend - Dev"
    needs: [terraform, test]
    # Only run this job when the pull request is merged or on direct push to dev
    if: (github.event_name == 'push' && github.ref == 'refs/heads/dev') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Workspace Environment Variable
        run: echo "WORKSPACE=${{ needs.terraform.outputs.environment }}" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Enable Corepack
        run: |
          corepack enable
          yarn --version
        
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Frontend for Dev Environment
        run: |
          # Create a temporary .env.sentry-build-plugin file with Sentry configuration
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" > .env.sentry-build-plugin
          echo "SENTRY_ORG=${{ secrets.SENTRY_ORG }}" >> .env.sentry-build-plugin
          echo "SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}" >> .env.sentry-build-plugin
          
          # Create or update the config/.env.dev.anv file
          mkdir -p config
          echo "VITE_API_URL=${{ secrets.VITE_API_URL_DEV }}" > config/.env.dev.anv
          echo "VITE_SENTRY_DSN=${{ secrets.VITE_SENTRY_DSN }}" >> config/.env.dev.anv
          
          # Run the dev-specific build
          yarn dev:build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to S3
        run: |
          # Use the S3 bucket name from terraform job
          S3_BUCKET="rizzlers-ibe-frontend-${{ env.WORKSPACE }}"
          
          echo "Deploying to S3 bucket: $S3_BUCKET"
          aws s3 sync ./dist/ s3://$S3_BUCKET/ --delete
        
      - name: Invalidate CloudFront Cache
        run: |
          # Get the S3 bucket name
          S3_BUCKET="rizzlers-ibe-frontend-${{ env.WORKSPACE }}"
          
          # Find CloudFront distribution directly from AWS API
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Origins.Items[].DomainName, '$S3_BUCKET')].Id" --output text)
          
          if [ -n "$DISTRIBUTION_ID" ]; then
            echo "Found distribution ID: $DISTRIBUTION_ID"
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
          else
            echo "No CloudFront distribution found associated with $S3_BUCKET"
            echo "List of CloudFront distributions:"
            aws cloudfront list-distributions --query "DistributionList.Items[].{Id:Id, Domain:DomainName, Origins:Origins.Items[].DomainName}" --output json
            echo "Skipping invalidation"
          fi
        continue-on-error: true

      - name: Deployment Info
        run: |
          echo "Frontend deployed to ${{ env.WORKSPACE }} environment:"
          echo "S3 Bucket: rizzlers-ibe-frontend-${{ env.WORKSPACE }}"
          if [ -n "${{ env.CLOUDFRONT_DOMAIN }}" ]; then
            echo "CloudFront URL: https://${{ env.CLOUDFRONT_DOMAIN }}"
          else
            echo "CloudFront distribution not available yet"
          fi 