name: "Initial Infrastructure Setup"

on:
  # Trigger on push to dev branch for terraform changes
  push:
    branches:
      - dev
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  
  # Manual trigger for infrastructure setup
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev/qa)'
        required: true
        type: choice
        options:
          - dev
          - qa

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  TERRAFORM_VERSION: "1.5.0"

jobs:
  terraform:
    name: "Setup AWS Infrastructure"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
          role-session-name: GithubActionsSession

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Get Environment
        id: env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Init
        working-directory: terraform/frontend
        run: |
          terraform init
          terraform workspace select ${{ steps.env.outputs.ENVIRONMENT }} || terraform workspace new ${{ steps.env.outputs.ENVIRONMENT }}

      - name: Terraform Plan
        working-directory: terraform/frontend
        run: |
          terraform plan \
            -var="environment=${{ steps.env.outputs.ENVIRONMENT }}" \
            -var="frontend_bucket_name=rizzlers-frontend" \
            -out=tfplan

      - name: Manual Approval for QA
        if: steps.env.outputs.ENVIRONMENT == 'qa'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: GaganChKick6378
          minimum-approvals: 1
          issue-title: "Deploy Infrastructure to QA"
          issue-body: |
            Please approve the initial infrastructure deployment to QA environment.
            This will set up:
            - S3 bucket for frontend hosting
            - CloudFront distribution
            - CodeBuild/CodePipeline for automated deployments
            - Required IAM roles and policies

      - name: Terraform Apply
        working-directory: terraform/frontend
        run: terraform apply -auto-approve tfplan 